name: build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Build
        run: |
          bundle install
          bundle exec jekyll build
