name: gem

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Build
        run: |
          bundle install
          gem build *.gemspec

      - name: Publish to GitHub Packages
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}
        run: |
          mkdir -p ~/.gem/
          touch ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > ~/.gem/credentials
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        run: |
          mkdir -p ~/.gem/
          touch ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > ~/.gem/credentials
          gem push *.gem
