name: github-pages

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  github-pages:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses:  helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
